version:  '3.7'

services:
  mysql:
    image: mysql:5.7
    restart: on-failure
    ports:
      - 127.0.0.1:3307:3306
    volumes:
      - db:/var/lib/mysql
    environment:
       - MYSQL_ALLOW_EMPTY_PASSWORD=1

  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    container_name: user-management-nginx
    volumes:
      - ./web:/usr/src/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8000:80
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    volumes:
      - .:/usr/src/app
    container_name: user-management-php-fpm
    user: 1000:1000
    env_file:
      - .env
    depends_on:
      - mysql

volumes:
  db:
