# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        ManagementBundle\Entity\User:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        db_provider:
            entity:
                class: ManagementBundle:User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: db_provider
            form_login:
                login_path: /
                check_path: /
                default_target_path: /admin
                always_use_default_target_path: true
            logout:
                path: /logout

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, IS_AUTHENTICATED_FULLY]

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN}
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY}
